In [1]:
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

/root/miniconda3/envs/llm/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
# /data/nvme3n1p1/adal_workspace/new_era_of_3.2/torchtune/checkpoints/llama3_2_1b_Instruct

In [14]:
from safetensors import safe_open
checkpoint_path = '/data/nvme3n1p1/adal_workspace/new_era_of_3.2/torchtune/checkpoints/llama3_2_1b_Instruct/model.safetensors'
result = {}
with safe_open(checkpoint_path, framework="pt", device="cpu") as f:
    for k in f.keys():
        result[k] = f.get_tensor(k)
    state_dict = result


In [15]:
state_dict

{'model.embed_tokens.weight': tensor([[ 3.1281e-03,  1.7822e-02,  2.0996e-02,  ..., -5.2185e-03,
          -4.1992e-02, -3.3447e-02],
         [ 2.3682e-02, -2.2949e-02,  1.9897e-02,  ..., -9.4604e-03,
          -2.2125e-03, -3.9551e-02],
         [ 1.4465e-02,  1.0559e-02,  9.8267e-03,  ...,  6.8359e-03,
          -1.1597e-02,  5.7983e-03],
         ...,
         [-1.0580e-06,  1.0620e-02, -1.9043e-02,  ...,  1.3885e-03,
          -1.7700e-03,  9.7046e-03],
         [-1.3635e-06,  1.0620e-02, -1.9043e-02,  ...,  1.3885e-03,
          -1.7700e-03,  9.7046e-03],
         [-1.1921e-06,  1.0620e-02, -1.9043e-02,  ...,  1.3885e-03,
          -1.7700e-03,  9.7046e-03]], dtype=torch.bfloat16),
 'model.layers.0.input_layernorm.weight': tensor([0.1543, 0.1826, 0.2559,  ..., 0.2168, 0.2080, 0.1494],
        dtype=torch.bfloat16),
 'model.layers.0.mlp.down_proj.weight': tensor([[-0.0269,  0.0176, -0.0003,  ..., -0.0194,  0.0115,  0.0058],
         [ 0.0156, -0.0057,  0.0072,  ..., -0.0233,  0.00

In [10]:
checkpoint = torch.load('/data/nvme3n1p1/adal_workspace/new_era_of_3.2/torchtune/checkpoints/llama3_2_1b_Instruct/model.safetensors') 
model_hf = AutoModelForCausalLM.from_pretrained("/data/nvme2n1p1/hub/models--meta-llama--Llama-3.2-1B-Instruct/snapshots/e9f8effbab1cbdc515c11ee6e098e3d5a9f51e14")

/tmp/ipykernel_259719/3954112628.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load('/data/nvme3n1p1/adal_workspace/new_era_of_3.2/torchtune/checkpo

UnpicklingError: invalid load key, '\xa0'.

In [12]:
model_hf.state_dict()

OrderedDict([('model.embed_tokens.weight',
              tensor([[ 3.1281e-03,  1.7822e-02,  2.0996e-02,  ..., -5.2185e-03,
                       -4.1992e-02, -3.3447e-02],
                      [ 2.3682e-02, -2.2949e-02,  1.9897e-02,  ..., -9.4604e-03,
                       -2.2125e-03, -3.9551e-02],
                      [ 1.4465e-02,  1.0559e-02,  9.8267e-03,  ...,  6.8359e-03,
                       -1.1597e-02,  5.7983e-03],
                      ...,
                      [-1.0580e-06,  1.0620e-02, -1.9043e-02,  ...,  1.3885e-03,
                       -1.7700e-03,  9.7046e-03],
                      [-1.3635e-06,  1.0620e-02, -1.9043e-02,  ...,  1.3885e-03,
                       -1.7700e-03,  9.7046e-03],
                      [-1.1921e-06,  1.0620e-02, -1.9043e-02,  ...,  1.3885e-03,
                       -1.7700e-03,  9.7046e-03]])),
             ('model.layers.0.self_attn.q_proj.weight',
              tensor([[-0.0179,  0.0066,  0.0247,  ..., -0.0087, -0.0117,  0.0201],
 

In [7]:
len(checkpoint)

146

In [8]:
set(model_hf.state_dict().keys()) - set(checkpoint.keys())

{'lm_head.weight'}

In [41]:
torch.save(checkpoint, "/data/nvme3n1p1/adal_workspace/new_era_of_3.2/torchtune/checkpoints/new_era_1b_sft/hf_model_0001_x.pt")

In [42]:
checkpoint

{'model.embed_tokens.weight': tensor([[-0.0040,  0.0178,  0.0210,  ...,  0.0022, -0.0420, -0.0334],
         [ 0.0237, -0.0229,  0.0199,  ..., -0.0095, -0.0023, -0.0396],
         [ 0.0145,  0.0106,  0.0098,  ...,  0.0041, -0.0116,  0.0021],
         ...,
         [ 0.0020,  0.0106, -0.0190,  ..., -0.0009, -0.0039,  0.0097],
         [ 0.0020,  0.0106, -0.0190,  ..., -0.0009, -0.0039,  0.0097],
         [ 0.0020,  0.0106, -0.0190,  ..., -0.0009, -0.0039,  0.0097]],
        dtype=torch.bfloat16),
 'model.layers.0.self_attn.q_proj.weight': tensor([[-0.0179,  0.0078,  0.0247,  ..., -0.0087, -0.0117,  0.0201],
         [ 0.0122,  0.0593,  0.0552,  ..., -0.0332, -0.0154,  0.0108],
         [ 0.0178,  0.0155,  0.0344,  ..., -0.0386, -0.0386, -0.0276],
         ...,
         [ 0.0298,  0.0352,  0.0713,  ..., -0.0718, -0.0265, -0.0287],
         [ 0.0226, -0.0248,  0.0352,  ..., -0.0120, -0.0287, -0.0148],
         [-0.0258, -0.0537, -0.0131,  ...,  0.0542,  0.0096, -0.0024]],
        dtype=to

In [43]:
model_hf.state_dict()["lm_head.weight"]

tensor([[ 3.1281e-03,  1.7822e-02,  2.0996e-02,  ..., -5.2185e-03,
         -4.1992e-02, -3.3447e-02],
        [ 2.3682e-02, -2.2949e-02,  1.9897e-02,  ..., -9.4604e-03,
         -2.2125e-03, -3.9551e-02],
        [ 1.4465e-02,  1.0559e-02,  9.8267e-03,  ...,  6.8359e-03,
         -1.1597e-02,  5.7983e-03],
        ...,
        [-1.0580e-06,  1.0620e-02, -1.9043e-02,  ...,  1.3885e-03,
         -1.7700e-03,  9.7046e-03],
        [-1.3635e-06,  1.0620e-02, -1.9043e-02,  ...,  1.3885e-03,
         -1.7700e-03,  9.7046e-03],
        [-1.1921e-06,  1.0620e-02, -1.9043e-02,  ...,  1.3885e-03,
         -1.7700e-03,  9.7046e-03]])

In [44]:
model_hf.state_dict()

OrderedDict([('model.embed_tokens.weight',
              tensor([[ 3.1281e-03,  1.7822e-02,  2.0996e-02,  ..., -5.2185e-03,
                       -4.1992e-02, -3.3447e-02],
                      [ 2.3682e-02, -2.2949e-02,  1.9897e-02,  ..., -9.4604e-03,
                       -2.2125e-03, -3.9551e-02],
                      [ 1.4465e-02,  1.0559e-02,  9.8267e-03,  ...,  6.8359e-03,
                       -1.1597e-02,  5.7983e-03],
                      ...,
                      [-1.0580e-06,  1.0620e-02, -1.9043e-02,  ...,  1.3885e-03,
                       -1.7700e-03,  9.7046e-03],
                      [-1.3635e-06,  1.0620e-02, -1.9043e-02,  ...,  1.3885e-03,
                       -1.7700e-03,  9.7046e-03],
                      [-1.1921e-06,  1.0620e-02, -1.9043e-02,  ...,  1.3885e-03,
                       -1.7700e-03,  9.7046e-03]])),
             ('model.layers.0.self_attn.q_proj.weight',
              tensor([[-0.0179,  0.0066,  0.0247,  ..., -0.0087, -0.0117,  0.0201],
 

In [45]:
checkpoint

{'model.embed_tokens.weight': tensor([[-0.0040,  0.0178,  0.0210,  ...,  0.0022, -0.0420, -0.0334],
         [ 0.0237, -0.0229,  0.0199,  ..., -0.0095, -0.0023, -0.0396],
         [ 0.0145,  0.0106,  0.0098,  ...,  0.0041, -0.0116,  0.0021],
         ...,
         [ 0.0020,  0.0106, -0.0190,  ..., -0.0009, -0.0039,  0.0097],
         [ 0.0020,  0.0106, -0.0190,  ..., -0.0009, -0.0039,  0.0097],
         [ 0.0020,  0.0106, -0.0190,  ..., -0.0009, -0.0039,  0.0097]],
        dtype=torch.bfloat16),
 'model.layers.0.self_attn.q_proj.weight': tensor([[-0.0179,  0.0078,  0.0247,  ..., -0.0087, -0.0117,  0.0201],
         [ 0.0122,  0.0593,  0.0552,  ..., -0.0332, -0.0154,  0.0108],
         [ 0.0178,  0.0155,  0.0344,  ..., -0.0386, -0.0386, -0.0276],
         ...,
         [ 0.0298,  0.0352,  0.0713,  ..., -0.0718, -0.0265, -0.0287],
         [ 0.0226, -0.0248,  0.0352,  ..., -0.0120, -0.0287, -0.0148],
         [-0.0258, -0.0537, -0.0131,  ...,  0.0542,  0.0096, -0.0024]],
        dtype=to

In [46]:
import numpy as np

# Your token lists
tokens_p = [1, 22, 3, 3, 4, 6]
tokens_l = [4, 6]

# Step 1: Find positions in tokens_p where tokens_l tokens are located
positions_to_mask = [i for i, token in enumerate(tokens_p) if token in tokens_l]

# Step 2: Determine the number of rows for the mask matrix
N = len(positions_to_mask) + 1  # Number of rows in the mask matrix
seq_len = len(tokens_p)         # Length of tokens_p

# Step 3: Initialize a mask of all True values
mask = np.ones((N, seq_len), dtype=bool)

# Step 4: Set positions to False progressively
for i in range(N):
    indices_to_false = positions_to_mask[i:]
    mask[i, indices_to_false] = False

# Output the mask
print(mask)


[[ True  True  True  True False False]
 [ True  True  True  True  True False]
 [ True  True  True  True  True  True]]


In [49]:
mask = torch.triu(torch.ones(10, 10), diagonal=4)

In [51]:
exp = mask == 0

In [52]:
exp

tensor([[ True,  True,  True,  True, False, False, False, False, False, False],
        [ True,  True,  True,  True,  True, False, False, False, False, False],
        [ True,  True,  True,  True,  True,  True, False, False, False, False],
        [ True,  True,  True,  True,  True,  True,  True, False, False, False],
        [ True,  True,  True,  True,  True,  True,  True,  True, False, False],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True, False],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True]])